### PR TITLE
First step at supporting aiy-voicebonnet

### PR DESCRIPTION
**Pull request by builderjer**
- respeaker 4mic and 6mic i2c numbers reversed
- fixed `i2cdetect` command with bus number

### CODE REVIEW

**Review by j1nx — APPROVED** [review]
Interesting. If this is tested and works (flipping 4mic and 6mic), then I have the same mistake on buildroot OS level;
https://github.com/OpenVoiceOS/ovos-buildroot/blob/develop/buildroot-external/board/raspberrypi/rootfs-overlay/usr/libexec/ovos-i2csound

I do not have a voicebonnet, so can't check that code. I do have the Chatterbox bonnet but that one is undetectable.

@builderjer What is needed on an OS level to configure that HAT? Then I can add the bonnet to the above script as well.

**Comment by builderjer** [comment]
I have the voicebonnet and a 4-mic respeaker to test with. soon a voice hat also and will add that detection.

The voicebonnet needs drivers from [this fork](https://github.com/viraniac/aiyprojects-raspbian) of aiyprojects.  I got the speaker and mic to work pretty easy, and have been working on the LED button.  a multi-colored led on the bonnet, not sure of the hat yet.  I needed to change permissions somewhere though.  Viraniac also made a deb file for the bonnet which was nice of him.  https://github.com/viraniac/aiy-voicebonnet-soundcard-dkms/releases/tag/3.0-1.1-beta

**Comment by builderjer** [comment]
just got the voicehat v1.  It does not register with i2cdetect, but it does work with just the overlay `googlevoicehat-soundcard`. So I won't be adding any additions to this PR unless the testing shows something to be wrong

**Comment by j1nx** [comment]
So, the v2 hat can be detected, the v1 cannot?

I can confirm the v1, however do not have a v2 to test.

**Comment by builderjer** [comment]
Yes, that is correct.  My V1 is NOT detected with `i2cdetect`, but the V2 bonnet is. I only added the mic detection, it also shows the speaker and the led in the i2c bus. I can add those if you want.

**Comment by viraniac** [comment]
> Yes, that is correct. My V1 is NOT detected with `i2cdetect`, but the V2 bonnet is. I only added the mic detection, it also shows the speaker and the led in the i2c bus. I can add those if you want.

Incase you are feeling brave enough to enable autodetection for Voice Hat v1,  please follow the instructions provided [here](https://github.com/viraniac/aiyprojects-raspbian/blob/aiyprojects/HACKING.md#appendix-hacking-aiy-voice-kit-v1-voice-hat-for-autodetection)

**Comment by builderjer** [comment]
Hmmm, maybe I will try that with mine, and then at least we can write the code to support this.  Then if anybody wants to do so, they can.

**Comment by viraniac** [comment]
Out of curiosity and I might be missing the bigger picture here, but why are you using i2cdetect to check whether aiy voice_bonnet is connected or not? Cant you use the contents of `/proc/device-tree/hat/product` file?

**Comment by builderjer** [comment]
I was emulating the code that was written for other devices.  I will check that when I hook one up again.  Thanks for the tip

**Comment by JarbasAl** [comment]
> /proc/device-tree/hat/

this only works after the dtoverlay is added to boot/config.txt right?

we want to detect this before that step, to automatically configure whatever is needed, but @j1nx is the one to explain better the constraints

**Comment by viraniac** [comment]
> this only works after the dtoverlay is added to boot/config.txt right?

As far as I can recall and assuming my understanding is correct, dtoverlay has nothing to do with it. I believe it is populated by the raspberrypi's bootloader after reading the hat's eeprom. The eeprom may or may not contain the dtoverlay dtb. Like in case of voice-hat v1, it doesn't contain the dtb and hence we manually have to add the dtoverlay. But even before adding dtoverlay manually, the `/proc/device-tree/hat` directory will exist if the raspberrypi bootloader was able to read the eeprom

**Comment by builderjer** [comment]
I have the voice hat v1 installed right now on a pi3b, and `/proc/device-tree/hat` is not there.  I checked before I added the dtoverlay, and after.  I does not show up there.  Is that because I did not flash the hat, (yet), like in your `HACKING.md`.

**Comment by viraniac** [comment]
Thats weird. Do you have force_eeprom_read or disable_poe_fan in your
config.txt?

Maybe you can share the config.txt and the os you are using and I can try
to troubleshoot it tomorrow.

**Comment by builderjer** [comment]
no `force_eeprom_read` or `disable_poe_fan`, I just used the original `HACKING.md` instructions for installing it, and it works good. I just can't detect it.  Should I add one of those?

As for what os?  It is a [custom raspbian image](https://github.com/OpenVoiceOS/raspbian-ovos) built with pi-gen 

```
cat /boot/config.txt 
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
#dtparam=audio=on

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

# Run in 64-bit mode
arm_64bit=1

# Disable compensation for displays with overscan
disable_overscan=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[all]

[pi4]
# Run as fast as firmware / board allows
arm_boost=1

[all]

[pi0]
arm_64bit=0

[all]

dtoverlay=googlevoicehat-soundcard
```

**Comment by viraniac** [comment]
Ok... Do you by any chance have multiple hats connected at the same time?
Like if i recall correctly,, last time you had both poe and bonnet
connected at the same time.

If thats also not the case then I will try it out again tomorrow. Have to
sleep now its 3AM here :) zZZ

**Comment by builderjer** [comment]
no, just the voice hat v1

**Comment by viraniac** [comment]
Alright. I will have to simulate what you have and troubleshoot the same.
Could you please backup and upload your hat's eeprom? I will flash it on my
hat tomorrow and see whats wrong with it.

You can follow the first 3 steps from
https://github.com/viraniac/aiyprojects-raspbian/blob/aiyprojects/HACKING.md#appendix-hacking-aiy-voice-kit-v1-voice-hat-for-autodetection
to backup your eeprom

**Comment by builderjer** [comment]
eeprom backup
https://drive.google.com/file/d/1nGzSZzK5WWif0CS_NRa-SZ3xSXr505QU/view?usp=sharing

**Comment by viraniac** [comment]
> eeprom backup https://drive.google.com/file/d/1nGzSZzK5WWif0CS_NRa-SZ3xSXr505QU/view?usp=sharing

This is weird. Your eeprom is completely empty. Mine had the hat metadata present in it. [Here](https://drive.google.com/file/d/1wQhPsG8GLtYsWXsUCfZM-AMvHxlkf9hl/view?usp=sharing) is my stock eeprom image for comparision

**Comment by builderjer** [comment]
I think I will flash like your instructions describe and see what shows up then.  Ya, mine was unreadable, I thought it was supposed to be that way.  It'll be later today though

**Comment by builderjer** [comment]
Not sure why the build tests are still failing, but without this, the ReSpeaker 4mic and 6mic are reversed, and will be configured wrong on boot, and by the PHAL plugin associated with them.

**Comment by builderjer** [comment]
Closing this as there is `ovos-i2cdetect` now

**Pull request closed without merging**
