### PR TITLE
sj201 v6 and v10 division

### PR DESCRIPTION
**Pull request by builderjer**
added sj201v10 detection.

This helps with plugin validation.

### CODE REVIEW

**Comment by builderjer** [comment]
Is this failing because it is from my personal repo? and not from ovos?

**Comment by JarbasAl** [comment]
i still think these should be defined in the individual plugins and this file deleted from here

only the mk2 plugins need to check for a mk2.... doesnt make sense to be in PHAL.

also plugins should only need to import from OPM, not from the PHAL code  (this is true for all plugins and other services)

**Comment by builderjer** [comment]
I feel that it should be shared code somewhere in the ovos repos. OPM makes sense to me more than individual packages copying the same thing. This allows for multiple mk2 plug-ins to do an import, instead of duplicating code.

**Comment by JarbasAl** [comment]
1 line of code `'i2cdetect -y -a 1 0x04 0x04 | egrep "(04|UU)" | awk \'{print $2}\''`  used in 2 repos at best  (fan and leds) is really not worth packaging IMHO.... 

conceptually doesnt fit in OPM repos either, in the sense it is not a shared util for all plugins, same argument done for the led and fan stuff

perhaps a dedicated tiny library can be created, just to have the i2c checks available in a single place with 0 dependencies, making it useful also for non OVOS projects etc

**Comment by builderjer** [comment]
I can go for that for sure

**Comment by builderjer** [comment]
depreciated detection to move to its own repo
https://github.com/OpenVoiceOS/ovos-i2c-detection

**Pull request merged**
